// Bug fix: DECISIONS was referenced in Dashboard but never defined
export const DECISIONS = [
  {
    id: 'buy_stock',
    name: '自社株買い',
    desc: '資金を投じて自社株を買い戻し、株価を20%引き上げる。',
    lpCost: 30,
    moneyCost: 5000,
    req: null,
    action: 'buy_stock',
  },
  {
    id: 'lobby_eu',
    name: 'EU規制ロビー活動',
    desc: '欧州の環境規制によるコスト増をロビー活動で撤廃する。',
    lpCost: 50,
    moneyCost: 8000,
    req: (s) => s.euExtraCost > 0,
    action: 'lobby_eu',
  },
  {
    id: 'end_strike',
    name: 'ストライキ緊急解決',
    desc: '待遇改善の費用を計上し、ストライキを即時終結させる。',
    lpCost: 40,
    moneyCost: 10000,
    req: (s) => s.flags.isStrike,
    action: 'end_strike',
  },
  {
    id: 'mega_ad',
    name: '大規模広告キャンペーン',
    desc: '全市場で緊急の広告攻勢をかけ、全シェアを15%底上げする。',
    lpCost: 60,
    moneyCost: 15000,
    req: null,
    action: 'mega_ad',
  },
  {
    id: 'internal_reform',
    name: '内部組織改革',
    desc: '社内の部門連携を強化し、サイロ化を抑制する。',
    lpCost: 40,
    moneyCost: 10000,
    req: null,
    action: 'internal_reform',
  },
  {
    id: 'price_war',
    name: '価格攻勢',
    desc: '販売価格を下げて短期的に競合シェアを奪う。利益は減少する。',
    lpCost: 50,
    moneyCost: 12000,
    req: null,
    action: 'price_war',
  },
];
