export const AI_COMPANIES = {
  mony: {
    name: 'Mony', color: 'bg-indigo-500', textColor: 'text-indigo-400',
    trait: 'バランス型', updateChance: 0.025, appealMod: 1.0, strongMarket: 'jp',
    prefixes: ['Walk', 'Sound', 'Mony', 'Play', 'Xperia'],
    appearsYear: 1946, disappearsYear: 9999,
    regions: { jp: 1946, na: 1960, eu: 1965 },
    stockBase: 95, revenueBase: 80000,
    strengths: ['日本市場でのブランド力', 'ウォークマン型ポータブル機器の先駆者', '音響・映像の高品質技術'],
    history: [
      { year: 1968, product: 'Walk Sound',     desc: 'ポータブルカセットプレーヤーの先駆け。' },
      { year: 1994, product: 'Play Station',   desc: '家庭用ゲーム機市場に参入。' },
    ],
  },
  philis: {
    name: 'Philis', color: 'bg-cyan-500', textColor: 'text-cyan-400',
    trait: '手堅い欧州企業', updateChance: 0.020, appealMod: 0.9, strongMarket: 'eu',
    prefixes: ['Phil', 'Sense', 'Sonic', 'Euro'],
    appearsYear: 1946, disappearsYear: 2015,
    regions: { eu: 1946, na: 1950, jp: 1970 },
    stockBase: 120, revenueBase: 100000,
    strengths: ['欧州市場の絶対的支配', '音響・照明技術の先駆者', '安定した製品供給'],
    history: [
      { year: 1950, product: 'Phil Radio',     desc: '欧州中に普及した高品質なラジオ受信機。' },
      { year: 1982, product: 'Compact Disc',   desc: 'Mony社と共同でCD規格を策定。' },
    ],
  },
  natio: {
    name: 'Natio', color: 'bg-orange-500', textColor: 'text-orange-400',
    trait: '量産・手堅い', updateChance: 0.030, appealMod: 0.85, strongMarket: 'jp',
    prefixes: ['Pana', 'Natio', 'Lumix', 'Sonic'],
    appearsYear: 1946, disappearsYear: 9999,
    regions: { jp: 1946, na: 1970, eu: 1980 },
    stockBase: 110, revenueBase: 150000,
    strengths: ['家電の王様', '強力な系列店ネットワーク', '圧倒的な量産力'],
    history: [
      { year: 1955, product: 'Natio TV',       desc: '日本中の家庭にテレビを普及させた。' },
      { year: 2000, product: 'Pana Vision',    desc: '薄型テレビ戦争で一時的に主導権を握る。' },
    ],
  },
  motora: {
    name: 'Motora', color: 'bg-red-500', textColor: 'text-red-400',
    trait: '通信特化', updateChance: 0.020, appealMod: 1.0, strongMarket: 'na',
    prefixes: ['Moto', 'Dyna', 'Star', 'TAC'],
    appearsYear: 1946, disappearsYear: 2012,
    regions: { na: 1946, eu: 1980, jp: 1990 },
    stockBase: 150, revenueBase: 120000,
    strengths: ['北米の通信インフラ', '初期の携帯電話技術', '軍事・業務用の信頼性'],
    history: [
      { year: 1983, product: 'Dyna TAC',       desc: '世界初の商用携帯電話。' },
      { year: 2004, product: 'Moto RAZR',      desc: '超薄型ガラケーで一世を風靡する。' },
    ],
  },
  samstar: {
    name: 'Samstar', color: 'bg-blue-600', textColor: 'text-blue-400',
    trait: '量産・高頻度', updateChance: 0.040, appealMod: 0.8, strongMarket: 'eu',
    prefixes: ['Galaxy', 'Wave', 'Sam', 'Sonic', 'Z-Fold'],
    appearsYear: 1969, disappearsYear: 9999,
    regions: { eu: 1969, na: 1980, jp: 2000 },
    stockBase: 70, revenueBase: 210000,
    strengths: ['圧倒的な量産・コスト競争力', '欧州・新興国市場での普及率', '幅広いプロダクト'],
    history: [
      { year: 1969, product: 'Sam TV',         desc: '白黒テレビの量産で家電市場に参入。' },
      { year: 2011, product: 'Galaxy Z',       desc: 'スマートフォンで世界トップシェアを獲得。' },
    ],
  },
  commodo: {
    name: 'Commodo', color: 'bg-stone-500', textColor: 'text-stone-400',
    trait: 'デジタル特化', updateChance: 0.025, appealMod: 1.1, strongMarket: 'na',
    prefixes: ['Amiga', 'Com', 'Pet', 'VIC'],
    appearsYear: 1975, disappearsYear: 1994,
    regions: { na: 1975, eu: 1980 },
    stockBase: 80, revenueBase: 60000,
    strengths: ['初期PC市場の覇権', '低価格コンピュータ', 'ゲーム・ホビー市場'],
    history: [
      { year: 1982, product: 'Com 64',         desc: '世界で最も売れた単一モデルのパソコン。' },
      { year: 1985, product: 'Amiga',          desc: '圧倒的なグラフィック性能を持つPC。' },
    ],
  },
  nokio: {
    name: 'Nokio', color: 'bg-sky-400', textColor: 'text-sky-300',
    trait: 'モバイル全振り', updateChance: 0.035, appealMod: 1.1, strongMarket: 'eu',
    prefixes: ['Nok', 'Lumia', 'Symb', 'Mobi'],
    appearsYear: 1980, disappearsYear: 2014,
    regions: { eu: 1980, na: 1995, jp: 2000 },
    stockBase: 130, revenueBase: 160000,
    strengths: ['圧倒的な携帯電話シェア', '頑丈なハードウェア', '欧州市場の絶対的支配'],
    history: [
      { year: 1998, product: 'Nok 3210',       desc: '世界で最も売れた携帯電話の一つ。' },
      { year: 2007, product: 'Symb OS',        desc: '一時代を築いたモバイルOSだが、次第に衰退。' },
    ],
  },
  pineapple: {
    name: 'Pineapple', color: 'bg-zinc-300', textColor: 'text-zinc-300',
    trait: '革新重視', updateChance: 0.015, appealMod: 1.3, strongMarket: 'na',
    prefixes: ['Pine', 'iSound', 'Mac', 'Pod', 'iGlass'],
    appearsYear: 1976, disappearsYear: 9999,
    regions: { na: 1976, eu: 1985, jp: 1990 },
    stockBase: 320, revenueBase: 180000,
    strengths: ['デザイン力とブランド価値', '北米市場でのエコシステム支配', '高価格帯でも売れる革新力'],
    history: [
      { year: 1976, product: 'iSound Classic', desc: '初のコンシューマ向け音楽プレーヤー。' },
      { year: 2007, product: 'iGlass Pro',     duration: 5, desc: '携帯電話とインターネットを統合した革命的デバイス。' },
    ],
  },
  microhard: {
    name: 'Microhard', color: 'bg-emerald-500', textColor: 'text-emerald-400',
    trait: 'ソフトウェア', updateChance: 0.020, appealMod: 1.1, strongMarket: 'na',
    prefixes: ['Surface', 'Win', 'Micro', 'Zune', 'Holo'],
    appearsYear: 1975, disappearsYear: 9999,
    regions: { na: 1975, eu: 1980, jp: 1985 },
    stockBase: 415, revenueBase: 200000,
    strengths: ['ソフトウェアとクラウドの寡占', '法人・エンタープライズ市場', 'OSとOFFICEの強力なエコシステム'],
    history: [
      { year: 1975, product: 'Micro OS',       desc: 'PCオペレーティングシステムの標準を確立。' },
      { year: 2000, product: 'Win Office',     desc: 'ビジネス向けソフトウェアで世界を席巻。' },
    ],
  },
  googo: {
    name: 'Googo', color: 'bg-amber-500', textColor: 'text-amber-400',
    trait: '検索＆AI', updateChance: 0.030, appealMod: 1.2, strongMarket: 'na',
    prefixes: ['Pixel', 'Nexus', 'Chrom', 'Googo', 'Nest'],
    appearsYear: 1998, disappearsYear: 9999,
    regions: { na: 1998, eu: 2000, jp: 2002 },
    stockBase: 175, revenueBase: 250000,
    strengths: ['AI・検索エンジンの圧倒的シェア', '広告収益モデルの独占', 'AndroidエコシステムとクラウドAI'],
    history: [
      { year: 1998, product: 'Googo Search',   desc: '検索エンジンでインターネットの入り口を独占。' },
      { year: 2008, product: 'Chrom Book',     desc: 'Androidスマートフォン向けOSで世界標準に。' },
    ],
  },
  genera: {
    name: 'Genera', color: 'bg-slate-400', textColor: 'text-slate-300',
    trait: '巨大複合企業', updateChance: 0.015, appealMod: 0.9, strongMarket: 'na',
    prefixes: ['Gen', 'Elec', 'Watt', 'Volt'],
    appearsYear: 1946, disappearsYear: 2004,
    regions: { na: 1946, eu: 1960 },
    stockBase: 250, revenueBase: 300000,
    strengths: ['圧倒的な資本力', '北米家電市場の支配', 'インフラとの相乗効果'],
    history: [
      { year: 1950, product: 'Gen Fridge',     desc: '北米の家庭に普及した白物家電。' },
      { year: 1980, product: 'Gen TV',         desc: 'カラーテレビ市場で一定のシェアを獲得。' },
    ],
  },
  hitac: {
    name: 'Hitac', color: 'bg-rose-600', textColor: 'text-rose-400',
    trait: '重電・インフラ', updateChance: 0.020, appealMod: 0.85, strongMarket: 'jp',
    prefixes: ['Hit', 'Motor', 'Kira', 'Infra'],
    appearsYear: 1946, disappearsYear: 9999,
    regions: { jp: 1946, na: 1970, eu: 1980 },
    stockBase: 130, revenueBase: 170000,
    strengths: ['強靭なモーター技術', 'B2B市場からの安定収益', '品質の高さ'],
    history: [
      { year: 1958, product: 'Hitac Washer',   desc: '白物家電ブームを牽引。' },
      { year: 1990, product: 'Kira TV',        desc: '高画質テレビでブランドを確立。' },
    ],
  },
  siemen: {
    name: 'Siemen', color: 'bg-teal-500', textColor: 'text-teal-400',
    trait: '欧州の重鎮', updateChance: 0.015, appealMod: 0.85, strongMarket: 'eu',
    prefixes: ['Siem', 'Nix', 'Tele', 'Euro'],
    appearsYear: 1946, disappearsYear: 2005,
    regions: { eu: 1946, jp: 1980 },
    stockBase: 200, revenueBase: 250000,
    strengths: ['欧州の通信インフラ支配', '産業用機器との連携', '質実剛健な設計'],
    history: [
      { year: 1955, product: 'Tele Radio',     desc: '欧州で広く普及した通信機。' },
      { year: 1995, product: 'Siem Mobile',    desc: '初期の携帯電話市場で一定のシェアを獲得。' },
    ],
  },
  ninten: {
    name: 'Ninten', color: 'bg-fuchsia-500', textColor: 'text-fuchsia-400',
    trait: '娯楽特化', updateChance: 0.030, appealMod: 1.4, strongMarket: 'jp',
    prefixes: ['Boy', 'Enter', 'Play', 'Cube'],
    appearsYear: 1977, disappearsYear: 9999,
    regions: { jp: 1977, na: 1985, eu: 1990 },
    stockBase: 140, revenueBase: 90000,
    strengths: ['ゲーム機の圧倒的ブランド', '強力な自社ソフト', '子供から大人まで魅了するIP'],
    history: [
      { year: 1983, product: 'Family Enter',   desc: '家庭用ゲーム機市場を爆発的に拡大させた。' },
      { year: 1989, product: 'Game Boy',       desc: '携帯ゲーム機という新市場を創出。' },
    ],
  },
  berry: {
    name: 'Berry', color: 'bg-violet-600', textColor: 'text-violet-400',
    trait: 'ビジネス特化', updateChance: 0.025, appealMod: 1.2, strongMarket: 'na',
    prefixes: ['Black', 'Berry', 'Key', 'Secure'],
    appearsYear: 1999, disappearsYear: 2016,
    regions: { na: 1999, eu: 2002 },
    stockBase: 110, revenueBase: 80000,
    strengths: ['物理キーボードの快適性', '圧倒的なセキュリティ', '北米ビジネスマンの必須ツール'],
    history: [
      { year: 2002, product: 'Black Phone',    desc: 'メールが打てる携帯電話として大ヒット。' },
      { year: 2008, product: 'Berry Storm',    desc: 'タッチパネルの波に乗ろうとするも苦戦。' },
    ],
  }
};

export const CONTENT_INVESTMENTS = [
  { id: 'music_label',       name: '音楽レーベル買収',    cost: 15000, target: 'audio',        appealBuff: 1.3, desc: 'オーディオ機器の魅力度UP' },
  { id: 'game_dev',          name: 'ゲームスタジオ設立',  cost: 25000, target: 'digital',      appealBuff: 1.4, desc: 'デジタル機器の魅力度UP' },
  { id: 'movie_studio',      name: '映画スタジオ買収',    cost: 40000, target: 'video',        appealBuff: 1.2, desc: '全カテゴリの魅力度UP' },
  { id: 'streaming_service', name: 'ストリーミング網',    cost: 80000, target: 'smart_device', appealBuff: 1.5, desc: 'スマートデバイスの魅力度UP' },
];
