export const AI_COMPANIES = {
  toshiba: {
    name: 'Toshiba', color: 'bg-red-700', textColor: 'text-red-500',
    trait: 'バランス型', updateChance: 0.025, appealMod: 1.0, strongMarket: 'jp',
    prefixes: ['Dynabook', 'Regza', 'Toshiba', 'Satellite'],
    appearsYear: 1946, disappearsYear: 9999,
    regions: { jp: 1946, na: 1960, eu: 1965 },
    stockBase: 95, revenueBase: 80000,
    strengths: ['日本市場での強いブランド', 'ノートPCの先駆者', '幅広いインフラ技術'],
    history: [
      { year: 1985, product: 'Dynabook',      desc: 'ラップトップPCの先駆けとして市場をリード。' },
      { year: 2006, product: 'Regza TV',      desc: '高画質な液晶テレビでブランドを再構築。' },
    ],
  },
  philips: {
    name: 'Philips', color: 'bg-blue-500', textColor: 'text-blue-400',
    trait: '手堅い欧州企業', updateChance: 0.020, appealMod: 0.9, strongMarket: 'eu',
    prefixes: ['Philips', 'Senseo', 'Sonic', 'Euro'],
    appearsYear: 1946, disappearsYear: 2015,
    regions: { eu: 1946, na: 1950, jp: 1970 },
    stockBase: 120, revenueBase: 100000,
    strengths: ['欧州市場の絶対的支配', '音響・照明技術の先駆者', '安定した製品供給'],
    history: [
      { year: 1950, product: 'Phil Radio',     desc: '欧州中に普及した高品質なラジオ受信機。' },
      { year: 1982, product: 'Compact Disc',   desc: 'ソニー社と共同でCD規格を策定。' },
    ],
  },
  panasonic: {
    name: 'Panasonic', color: 'bg-blue-900', textColor: 'text-blue-400',
    trait: '量産・手堅い', updateChance: 0.030, appealMod: 0.85, strongMarket: 'jp',
    prefixes: ['Panasonic', 'National', 'Lumix', 'Technics'],
    appearsYear: 1946, disappearsYear: 9999,
    regions: { jp: 1946, na: 1970, eu: 1980 },
    stockBase: 110, revenueBase: 150000,
    strengths: ['家電の王様', '強力な系列店ネットワーク', '圧倒的な量産力'],
    history: [
      { year: 1955, product: 'National TV',    desc: '日本中の家庭にテレビを普及させた。' },
      { year: 2000, product: 'Viera',          desc: 'プラズマテレビで一時代を築く。' },
    ],
  },
  motorola: {
    name: 'Motorola', color: 'bg-red-500', textColor: 'text-red-400',
    trait: '通信特化', updateChance: 0.020, appealMod: 1.0, strongMarket: 'na',
    prefixes: ['Moto', 'Dyna', 'Star', 'RAZR'],
    appearsYear: 1946, disappearsYear: 2012,
    regions: { na: 1946, eu: 1980, jp: 1990 },
    stockBase: 150, revenueBase: 120000,
    strengths: ['北米の通信インフラ', '初期の携帯電話技術', '軍事・業務用の信頼性'],
    history: [
      { year: 1983, product: 'DynaTAC',        desc: '世界初の商用携帯電話。' },
      { year: 2004, product: 'RAZR',           desc: '超薄型携帯電話で世界的なヒット。' },
    ],
  },
  samsung: {
    name: 'Samsung', color: 'bg-blue-600', textColor: 'text-blue-400',
    trait: '量産・高頻度', updateChance: 0.040, appealMod: 0.8, strongMarket: 'eu',
    prefixes: ['Galaxy', 'Wave', 'Samsung', 'OLED', 'Z-Fold'],
    appearsYear: 1969, disappearsYear: 9999,
    regions: { eu: 1969, na: 1980, jp: 2000 },
    stockBase: 70, revenueBase: 210000,
    strengths: ['圧倒的な量産・コスト競争力', '欧州・新興国市場での普及率', '垂直統合によるスピード'],
    history: [
      { year: 1969, product: 'Samsung TV',     desc: '白黒テレビの量産で家電市場に参入。' },
      { year: 2011, product: 'Galaxy S',       desc: 'スマートフォンで世界トップシェアを獲得。' },
    ],
  },
  nokia: {
    name: 'Nokia', color: 'bg-sky-400', textColor: 'text-sky-300',
    trait: 'モバイル全振り', updateChance: 0.035, appealMod: 1.1, strongMarket: 'eu',
    prefixes: ['Nokia', 'Lumia', 'Communicator', 'N-Gage'],
    appearsYear: 1980, disappearsYear: 2014,
    regions: { eu: 1980, na: 1995, jp: 2000 },
    stockBase: 130, revenueBase: 160000,
    strengths: ['圧倒的な携帯電話シェア', '頑丈なハードウェア', '欧州市場の絶対的支配'],
    history: [
      { year: 1998, product: 'Nokia 3210',     desc: '世界で最も売れた携帯電話の一つ。' },
      { year: 2007, product: 'Symbian OS',     desc: '一時代を築いたモバイルOSの王。' },
    ],
  },
  apple: {
    name: 'Apple', color: 'bg-zinc-300', textColor: 'text-zinc-400',
    trait: '革新重視', updateChance: 0.015, appealMod: 1.3, strongMarket: 'na',
    prefixes: ['Apple', 'iPod', 'Mac', 'iPhone', 'iPad'],
    appearsYear: 1976, disappearsYear: 9999,
    regions: { na: 1976, eu: 1985, jp: 1990 },
    stockBase: 320, revenueBase: 180000,
    strengths: ['デザイン力とブランド価値', '垂直統合のエコシステム', '圧倒的な利益率'],
    history: [
      { year: 1977, product: 'Apple II',       desc: '個人用コンピュータの普及を決定づけた。' },
      { year: 2007, product: 'iPhone',         desc: 'スマートフォン市場を創出し、世界を変えた。' },
    ],
  },
  microsoft: {
    name: 'Microsoft', color: 'bg-emerald-500', textColor: 'text-emerald-400',
    trait: 'ソフトウェア', updateChance: 0.020, appealMod: 1.1, strongMarket: 'na',
    prefixes: ['Surface', 'Windows', 'Xbox', 'Office', 'Azure'],
    appearsYear: 1975, disappearsYear: 9999,
    regions: { na: 1975, eu: 1980, jp: 1985 },
    stockBase: 415, revenueBase: 200000,
    strengths: ['ソフトウェアの事実上の標準', '法人市場の強力な基盤', 'プラットフォーム戦略'],
    history: [
      { year: 1985, product: 'Windows',        desc: 'GUIオペレーティングシステムの普及。' },
      { year: 2001, product: 'Xbox',           desc: '家庭用ゲーム機市場への参入。' },
    ],
  },
  google: {
    name: 'Google', color: 'bg-amber-500', textColor: 'text-amber-400',
    trait: '検索＆AI', updateChance: 0.030, appealMod: 1.2, strongMarket: 'na',
    prefixes: ['Pixel', 'Android', 'Chrome', 'Google', 'Nest'],
    appearsYear: 1998, disappearsYear: 9999,
    regions: { na: 1998, eu: 2000, jp: 2002 },
    stockBase: 175, revenueBase: 250000,
    strengths: ['インターネットの入り口を独占', '世界最大の広告プラットフォーム', 'Androidによるモバイル支配'],
    history: [
      { year: 1998, product: 'Google Search',   desc: '世界を変えた検索エンジン。' },
      { year: 2008, product: 'Android OS',      desc: 'モバイルOSで世界トップシェアに。' },
    ],
  },
  ge: {
    name: 'GE', color: 'bg-slate-400', textColor: 'text-slate-300',
    trait: '巨大複合企業', updateChance: 0.015, appealMod: 0.9, strongMarket: 'na',
    prefixes: ['GE', 'General', 'Electric', 'Hotpoint'],
    appearsYear: 1946, disappearsYear: 2004,
    regions: { na: 1946, eu: 1960 },
    stockBase: 250, revenueBase: 300000,
    strengths: ['圧倒的な資本力', '北米家電市場の支配', 'インフラとの相乗効果'],
    history: [
      { year: 1950, product: 'GE Fridge',      desc: '北米の家庭に普及した白物家電。' },
      { year: 1980, product: 'CT Scanner',     desc: '医療・産業分野での高い技術力。' },
    ],
  },
  hitachi: {
    name: 'Hitachi', color: 'bg-rose-600', textColor: 'text-rose-400',
    trait: '重電・インフラ', updateChance: 0.020, appealMod: 0.85, strongMarket: 'jp',
    prefixes: ['Hitachi', 'Wooo', 'Motor', 'Infra'],
    appearsYear: 1946, disappearsYear: 9999,
    regions: { jp: 1946, na: 1970, eu: 1980 },
    stockBase: 130, revenueBase: 170000,
    strengths: ['強靭なモーター技術', 'B2B市場からの安定収益', '質実剛健な設計'],
    history: [
      { year: 1958, product: 'Automatic Washer', desc: '白物家電ブームを牽引。' },
      { year: 1990, product: 'Wooo TV',          desc: '高品質な映像技術でシェアを獲得。' },
    ],
  },
  siemens: {
    name: 'Siemens', color: 'bg-teal-500', textColor: 'text-teal-400',
    trait: '欧州の重鎮', updateChance: 0.015, appealMod: 0.85, strongMarket: 'eu',
    prefixes: ['Siemens', 'Nixdorf', 'Gigaset', 'Euro'],
    appearsYear: 1946, disappearsYear: 2005,
    regions: { eu: 1946, jp: 1980 },
    stockBase: 200, revenueBase: 250000,
    strengths: ['欧州の通信インフラ支配', '産業用機器との連携', 'ドイツの精密技術'],
    history: [
      { year: 1955, product: 'Tele Radio',      desc: '欧州で広く普及した通信機。' },
      { year: 1995, product: 'Siemens Mobile',  desc: '初期の携帯電話市場で一定のシェア。' },
    ],
  },
  nintendo: {
    name: 'Nintendo', color: 'bg-fuchsia-500', textColor: 'text-fuchsia-400',
    trait: '娯楽特化', updateChance: 0.030, appealMod: 1.4, strongMarket: 'jp',
    prefixes: ['GameBoy', 'NES', 'SNES', 'N64', 'Switch'],
    appearsYear: 1977, disappearsYear: 9999,
    regions: { jp: 1977, na: 1985, eu: 1990 },
    stockBase: 140, revenueBase: 90000,
    strengths: ['ゲーム機の圧倒的ブランド', '強力な自社ソフトIP', '独自の遊びの哲学'],
    history: [
      { year: 1983, product: 'Famicom',        desc: '家庭用ゲーム機市場を爆発的に拡大させた。' },
      { year: 1989, product: 'GameBoy',        desc: '携帯ゲーム機という新市場を創出。' },
    ],
  },
  blackberry: {
    name: 'BlackBerry', color: 'bg-violet-600', textColor: 'text-violet-400',
    trait: 'ビジネス特化', updateChance: 0.025, appealMod: 1.2, strongMarket: 'na',
    prefixes: ['BlackBerry', 'Curve', 'Bold', 'Passport'],
    appearsYear: 1999, disappearsYear: 2016,
    regions: { na: 1999, eu: 2002 },
    stockBase: 110, revenueBase: 80000,
    strengths: ['物理キーボードの快適性', '圧倒的なセキュリティ', '北米ビジネスマンの必須ツール'],
    history: [
      { year: 2002, product: 'BlackBerry 5810', desc: 'メールが打てる携帯電話として大ヒット。' },
      { year: 2008, product: 'Bold',             desc: 'ビジネススマートフォンの頂点を極める。' },
    ],
  }
};

export const CONTENT_INVESTMENTS = [
  { id: 'music_label',       name: 'ソニー・ミュージック設立', cost: 15000, target: 'audio',        appealBuff: 1.3, desc: 'オーディオ機器の魅力度UP' },
  { id: 'game_dev',          name: 'プレイステーション展開',  cost: 25000, target: 'digital',      appealBuff: 1.4, desc: 'デジタル機器の魅力度UP' },
  { id: 'movie_studio',      name: 'コロンビア・ピクチャーズ買収', cost: 40000, target: 'video',        appealBuff: 1.2, desc: '全カテゴリの魅力度UP' },
  { id: 'streaming_service', name: 'ソニー・ピクチャーズ・コア',    cost: 80000, target: 'smart_device', appealBuff: 1.5, desc: 'スマートデバイスの魅力度UP' },
];
